import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import ChatBox from "@/app/home/components/ChatBox";

const spaceGrotesk = Space_Grotesk({subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Saptash Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={spaceGrotesk.className}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
      >
        {children}
        <ChatBox />
      </ThemeProvider>
      </body>
    </html>
  );
}
